# see https://github.com/SymfonyCasts/reset-password-bundle/blob/main/config/packages/reset_password.yaml
symfonycasts_reset_password:
    request_password_repository: 'App\Repository\ResetPasswordRequestRepository'
    lifetime: 1800  # 30 minutes in seconds
    throttle_limit: 60  # 1 minute in seconds
    enable_garbage_collection: true
