# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
  # Put parameters here that don't need to change on each machine where the app is deployed
  profile_pictures_directory: "%kernel.project_dir%/public/uploads/profile_pictures"
  google_ai_api_key: '%env(GOOGLE_AI_API_KEY)%'
  google_ai_model: '%env(GOOGLE_AI_MODEL)%'
services:
  Symfony\Component\Finder\Finder:
    class: Symfony\Component\Finder\Finder
  App\Service\GeminiService:
        arguments:
            $httpClient: '@http_client'
  # Default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # Makes classes in src/ available to be used as services
  # This creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # Explicit service configuration for GeoapifyService
  App\Service\GeoapifyService:
    arguments:
      $geoapifyKey: "%env(GEOAPIFY_API_KEY)%"

  App\Service\TwilioService:
    arguments:
      $sid: "%env(TWILIO_SID)%"
      $authToken: "%env(TWILIO_AUTH_TOKEN)%"
      $fromNumber: "%env(TWILIO_PHONE_NUMBER)%"

  # Other service definitions can go here
    